export const ADD_FOOD_TO_BASKET ='ADD_FOOD_TO_BASKET';
export const REMOVE_FOOD_FROM_BASKET ='REMOVE_FOOD_FROM_BASKET';
export const CLEAN_BASKET ='CLEAN_BASKET';
export const FETCH_CATEGORIES_SUCCESS ='FETCH_CATEGORIES_SUCCESS';
export const FETCH_FOOD_SUCCESS ='FETCH_FOOD_SUCCESS';
export const LOAD_MORE_SUCCESS ='LOAD_MORE_SUCCESS';
export const FETCH_FOOD_BY_ID_SUCCESS ='FETCH_FOOD_BY_ID_SUCCESS';
export const SEARCH_FOOD ='SEARCH_FOOD';